<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\{User,Patient,Operator,Anesthesia,SurgicalTeam,SurgerySchedule,Shift,ShiftAssignment};
class DatabaseSeeder extends Seeder {
 public function run():void {
  User::updateOrCreate(['username'=>'admin'],['name'=>'Administrator','password'=>Hash::make('admin'),'permissions'=>['schedule.view','schedule.manage','master.manage','shift.manage','user.manage']]);
  $ops=[['name'=>'dr. Marina Paristiwati T, Sp.OG','license_no'=>'SIP-001','specialty'=>'Obgyn'],['name'=>'dr. Jimmy, M. Biomed, Sp.B','license_no'=>'SIP-002','specialty'=>'Bedah'],['name'=>'dr. Wahyudi, Sp.OG','license_no'=>'SIP-003','specialty'=>'Obgyn'],['name'=>'dr. Inayah Afrilia, Sp.OG','license_no'=>'SIP-004','specialty'=>'Obgyn']]; foreach($ops as $x)Operator::updateOrCreate(['name'=>$x['name']],$x);
  $anes=[['name'=>'dr. Marshelli Orlando, Sp.An','license_no'=>'AN-001','specialty'=>'Anestesi'],['name'=>'dr. Fandy Fadhilul A., MKM, M.KED(An), Sp.An-Ti','license_no'=>'AN-002','specialty'=>'Anestesi']];foreach($anes as $x)Anesthesia::updateOrCreate(['name'=>$x['name']],$x);
  $teams=[['name'=>'Tim Bedah A','members'=>['Adinda Mustika Dwi, A.md. Kep','Any Anisa, A.md. Kep']],['name'=>'Tim Bedah B','members'=>['Adinda Mustika Dwi, A.md. Kep','Sonia Aprilia, A.md. Kep']]];foreach($teams as $x)SurgicalTeam::updateOrCreate(['name'=>$x['name']],$x);
  $patients=[['medical_record_no'=>'RM-0001','name'=>'Ny. Siti Aisya','gender'=>'P','birth_date'=>'1998-10-01'],['medical_record_no'=>'RM-0002','name'=>'Nn. Nabila Putri Anjani','gender'=>'P','birth_date'=>'2003-04-01'],['medical_record_no'=>'RM-0003','name'=>'Tn. Ahmad Ridwan','gender'=>'L','birth_date'=>'1996-07-17'],['medical_record_no'=>'RM-0004','name'=>'Ny. Citra Jingga','gender'=>'P','birth_date'=>'1980-11-25'],['medical_record_no'=>'RM-0005','name'=>'Ny. Amelia Putri Ajelina','gender'=>'P','birth_date'=>'1999-02-30'],['medical_record_no'=>'RM-0006','name'=>'Tn. Niko Syaputra','gender'=>'L','birth_date'=>'1985-05-10'],['medical_record_no'=>'RM-0007','name'=>'Yn. Ericha Febriana','gender'=>'P','birth_date'=>'1985-10-05'],['medical_record_no'=>'RM-0008','name'=>'Ny. Dinda Ambarias Najwa','gender'=>'P','birth_date'=>'1985-10-05']];
  foreach($patients as $x){ if(!checkdate((int)substr($x['birth_date'],5,2),(int)substr($x['birth_date'],8,2),(int)substr($x['birth_date'],0,4))) $x['birth_date']='1999-02-28'; Patient::updateOrCreate(['medical_record_no'=>$x['medical_record_no']],$x); }
  foreach([['PAGI','07:00','14:00','#0d6efd'],['MIDEL','14:00','17:00','#6f42c1'],['SORE','17:00','23:00','#198754'],['MALAM','23:00','07:00','#212529']] as $x)Shift::updateOrCreate(['name'=>$x[0]],['start_time'=>$x[1],'end_time'=>$x[2],'color'=>$x[3]]);
  $date=now('Asia/Jakarta')->toDateString();$p=Patient::orderBy('id')->get();$o=Operator::all();$a=Anesthesia::all();$t=SurgicalTeam::all();$samples=[['09:00','G2 P1 Uk 37mg+ BSC < 2Tahun','SC','OK 1',false,0,0],['11:00','Tumor jaringan lunak','Eksisi Tumor','OK 2',true,1,1],['12:00','Hemoroid','Hemoroidektomi','OK 1',false,1,0],['13:00','G2 P1 Uk 37mg+ BSC < 2Tahun','SC','OK 3',false,2,1],['14:00','G2 P1 Uk 38mg+ BSC < 2Tahun','SC','OK 2',true,3,0],['15:00','Hemoroid','Hemoroidektomi','OK 1',false,1,1],['17:00','G2 P1 Uk 38mg+ BSC < 2Tahun','SC','OK 3',false,0,0],['19:00','G2 P1 Uk 38mg+ BSC < 2Tahun','SC','OK 2',false,2,0]];foreach($samples as $i=>$s)SurgerySchedule::updateOrCreate(['patient_id'=>$p[$i]->id,'operation_date'=>$date],['operation_time'=>$s[0],'diagnosis'=>$s[1],'procedure'=>$s[2],'ok_level'=>$s[3],'cito'=>$s[4],'operator_id'=>$o[$s[5]]->id,'anesthesia_id'=>$a[$s[6]]->id,'surgical_team_id'=>$t[$i%2]->id,'status'=>'Terjadwal']);
  foreach(Shift::all() as $shift){foreach(['Adinda Mustika Dwi, A.md. Kep','Sonia Aprilia, A.md. Kep','Desria Roza, A.md. Kep','Adelia Septiana, A.md. Kep'] as $name)ShiftAssignment::firstOrCreate(['shift_id'=>$shift->id,'staff_name'=>$name,'shift_date'=>$date],['staff_role'=>'Dinas']);}
 }
}
