@extends('layouts.admin') @section('title',$schedule->exists?'Edit Jadwal':'Jadwal Baru') @section('content')
<div class="card p-4"><form method="POST" action="{{ $schedule->exists?route('admin.schedules.update',$schedule):route('admin.schedules.store') }}">@csrf @if($schedule->exists) @method('PUT') @endif
<div class="row g-3"><div class="col-md-4"><label class="form-label">Pasien</label><select name="patient_id" id="patient_id" class="form-select" required><option value="">Pilih pasien...</option>@foreach($patients as $p)<option value="{{ $p->id }}" data-birth="{{ $p->birth_date->format('Y-m-d') }}" {{ old('patient_id',$schedule->patient_id)==$p->id?'selected':'' }}>{{ $p->name }} ({{ $p->gender }})</option>@endforeach</select><div class="small-muted mt-1">Umur otomatis dihitung dari tanggal lahir pasien.</div></div><div class="col-md-2"><label class="form-label">Umur</label><input id="age" class="form-control" readonly></div><div class="col-md-3"><label class="form-label">Tanggal Operasi</label><input type="date" name="operation_date" class="form-control" value="{{ old('operation_date',$schedule->operation_date?->format('Y-m-d')??request('date',now()->toDateString())) }}" required></div><div class="col-md-3"><label class="form-label">Jam</label><input type="time" name="operation_time" class="form-control" value="{{ old('operation_time',$schedule->operation_time) }}" required></div>
<div class="col-md-3"><label class="form-label">Ruang Operasi / OK</label><select name="ok_level" class="form-select"><option>OK 1</option><option>OK 2</option><option>OK 3</option></select></div><div class="col-md-5"><label class="form-label">Diagnosa</label><input name="diagnosis" class="form-control" value="{{ old('diagnosis',$schedule->diagnosis) }}"></div><div class="col-md-4"><label class="form-label">Tindakan</label><input name="procedure" class="form-control" value="{{ old('procedure',$schedule->procedure) }}" required></div>
<div class="col-md-4"><label class="form-label">Operator</label><select name="operator_id" class="form-select"><option value="">Pilih...</option>@foreach($operators as $x)<option value="{{ $x->id }}" {{ old('operator_id',$schedule->operator_id)==$x->id?'selected':'' }}>{{ $x->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Anestesi</label><select name="anesthesia_id" class="form-select"><option value="">Pilih...</option>@foreach($anesthesias as $x)<option value="{{ $x->id }}" {{ old('anesthesia_id',$schedule->anesthesia_id)==$x->id?'selected':'' }}>{{ $x->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Tim Bedah</label><select name="surgical_team_id" class="form-select"><option value="">Pilih...</option>@foreach($teams as $x)<option value="{{ $x->id }}" {{ old('surgical_team_id',$schedule->surgical_team_id)==$x->id?'selected':'' }}>{{ $x->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option>Terjadwal</option><option>Selesai</option><option>Batal</option></select></div><div class="col-md-3 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="cito" value="1" id="cito" {{ old('cito',$schedule->cito)?'checked':'' }}><label class="form-check-label" for="cito">CITO</label></div></div><div class="col-12"><label class="form-label">Catatan</label><textarea name="notes" class="form-control" rows="3">{{ old('notes',$schedule->notes) }}</textarea></div></div>
<div class="alert alert-info mt-3 mb-0"><i class="bi bi-shield-check me-1"></i> Bentrok otomatis dicek untuk ruang OK, operator, anestesi, dan tim bedah dengan durasi operasi 90 menit.</div><div class="mt-4 d-flex gap-2"><button class="btn btn-rs">Simpan</button><a href="{{ route('admin.schedules.index') }}" class="btn btn-outline-secondary">Batal</a></div></form></div>
@endsection
@push('scripts')<script>function calc(){let o=document.querySelector('#patient_id option:checked'),v=o?.dataset.birth;if(!v){document.getElementById('age').value='';return}let b=new Date(v+'T00:00:00'),n=new Date(),a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()==b.getMonth()&&n.getDate()<b.getDate()))a--;document.getElementById('age').value=a+' tahun';}document.getElementById('patient_id').addEventListener('change',calc);calc();</script>@endpush
